### ISSUE TITLE
General OpenGL Issue Tracker for missing function definitions

### ISSUE THREAD

**Issue by MrDiver** [ManimCommunity/manim#2708]
## Missing function declarations and mismatches between normal and opengl implementations of classes

Related to https://github.com/ManimCommunity/manim/milestone/10

**Please delete the functions from this text when they are not needed in the opengl part**

---

`OpenGLMobject` is Missing the following from `Mobject` (opengl_mobject.py)

- [ ] animation_overrides
- [ ] animation_override_for
- [ ] _add_intrinsic_animation_overrides
- [ ] add_animation_override
- [ ] __deepcopy__
- [ ] reset_points
- [ ] generate_points
- [ ] __getattr__
- [ ] get_array_attrs
- [ ] get_image
- [ ] show
- [ ] save_image
- [ ] apply_to_family
- [ ] repeat
- [ ] apply_points_function_about_point
- [ ] pose_at_angle
- [ ] set_colors_by_radial_gradient
- [ ] set_submobject_colors_by_radial_gradient
- [ ] to_original_color
- [ ] fade_to
- [ ] reduce_across_dimension
- [ ] nonempty_submobjects
- [ ] get_merged_array
- [ ] get_points_defining_boundary
- [ ] get_extremum_along_dim
- [ ] get_critical_point
- [ ] proportion_from_point
- [ ] has_no_points
- [ ] arrange_submobjects
- [ ] sort_submobjects
- [ ] shuffle_submobjects
- [ ] get_point_mobject
- [ ] align_points_with_larger
- [ ] align_submobjects
- [ ] null_point_align
- [ ] repeat_submobject
- [ ] interpolate_color

---

`OpenGLVMobject` is Missing the following from `VMobject` (opengl_vectorized_mobject.py)

- [ ] sheen_factor
- [ ] generate_rgbas_array
- [ ] update_rgbas_array
- [ ] set_background_stroke
- [ ] get_fill_rgbas
- [ ] get_stroke_rgbas
- [ ] set_sheen_direction
- [ ] rotate_sheen_direction
- [ ] set_sheen
- [ ] get_sheen_direction
- [ ] get_sheen_factor
- [ ] get_gradient_start_and_end_points
- [ ] color_using_background_image
- [ ] get_background_image
- [ ] match_background_image
- [ ] set_shade_in_3d
- [ ] clear_points
- [ ] append_points
- [ ] rotate
- [ ] scale_handle_to_anchor_distances
- [ ] consider_points_equals_2d
- [ ] get_cubic_bezier_tuples_from_points
- [ ] gen_cubic_bezier_tuples_from_points
- [ ] get_cubic_bezier_tuples
- [ ] _gen_subpaths_from_points
- [ ] gen_subpaths_from_points_2d
- [ ] get_points_defining_boundary
- [ ] align_rgbas
- [ ] get_point_mobject
- [ ] interpolate_color
- [ ] animation_overrides
- [ ] set_z_index
- [ ] set_z_index_by_z_coordinate
- [ ] get_nth_curve_length_pieces #2707

---

`OpenGLPMobject` is Missing the following from `PMobject` (opengl_point_cloud_mobject.py)

- [ ] set_color
- [ ] get_stroke_width
- [ ] set_stroke_width
- [ ] get_all_rgbas
- [ ] get_color
- [ ] align_points_with_larger
- [ ] get_point_mobject
- [ ] interpolate_color
- [ ] animation_overrides
- [ ] __abstractmethods__
- [ ] _abc_impl

`OpenGLPMobject` is Missing the following from `Mobject1D` (opengl_point_cloud_mobject.py)

- [ ] add_line
- [ ] animation_overrides
- [ ] __abstractmethods__
- [ ] _abc_impl

`OpenGLPMobject` is Missing the following from `Mobject2D` (opengl_point_cloud_mobject.py)

- [ ] animation_overrides
- [ ] __abstractmethods__
- [ ] _abc_impl

---

`OpenGLSurface` is Missing the following from `Surface` (opengl_surface.py)

- [ ] _get_u_values_and_v_values
- [ ] _setup_in_uv_space
- [ ] set_fill_by_checkerboard
- [ ] animation_overrides
- [ ] __abstractmethods__
- [ ] _abc_impl

---

# General Issues

- [ ] z_indexing in opengl renderer not implemented (order in which things are rendered)

---

Please link PR's related to this directly to the corresponding function
