### ISSUE TITLE
Add linting back to CI

### ISSUE THREAD

**Issue by Viicos** [ManimCommunity/manim#3622]
Following https://github.com/ManimCommunity/manim/pull/3620, would be great to enforce linting on CI.

I propose using Ruff instead of flake8, it would avoid having to install a bunch of plugins and `pyproject.toml` configuration is supported.

Format could be included as well if the diff isn't to big.

**Comment by behackl** [comment]
I like the idea and have heard many good things about `ruff`. It would be nice to see a branch with this!

**Comment by JasonGrace2282** [comment]
Tracking PRs:
If you want to help, just send a message here and I'll add your PR to the list :)
# Formatting
- [x] Add formatting configuration (#3777)
- [x] Format code + ignore diff (#3781)

# Linting
- [x] flake8-builtins (#3884)
- [x] flake8-bugbear (#3882)
- [x] flake8-comprehensions (#3882)
- [x] pycodestyle `E` (#3780)
- [x] pycodestyle `W` (#4276)
- [x] pyflakes (#3780)
- [x] isort (#3780)
- [ ] pylint
- [x] flake8-pytest-style (#3872)
- [x] pygrep hooks (#3923)
- [ ] ruff lint rules
- [x] flake8-simplify (#3873)
- [x] pyupgrade
- [x] pydocstyle (#3881)

**Comment by KaiqueDultra** [comment]
Hello @Viicos, @behackl and @JasonGrace2282, how are you? 

I was analyzing this issue and I found it very interesting! Maybe I could help with one of the following linting topics:

-  pycodestyle
-  pylint
-  ruff lint rules

I´m still analyzing the possibility of acting on this issue and as soon as I decide I will let you know. 

Thanks!

**Comment by KaiqueDultra** [comment]
Hello @Viicos, @behackl and @JasonGrace2282, how are you? 

As I mentioned in the above comment, I will help with this issue by working on:

- [ ]  pylint

I will implement Ruff linting CI to replace pylint and once I finished the code, I will create the PR.

Thanks, guys!

**Comment by KaiqueDultra** [comment]
Dears @behackl and @JasonGrace2282,

Don´t forget to link #4276 with the pycodestyle W rule in the linting list :-) 

Thanks!
