### ISSUE TITLE
Experimental Progress Tracker

### ISSUE THREAD

**Issue by JasonGrace2282** [ManimCommunity/manim#3817]
## Before merging into Main
- [X] Restructure the render loop to use `Manager`
- [ ] Double pass rendering to decouple `Scene` and `Manager`
- [ ] Rewrite VMobject to be renderer agnostic (in progress)
- [ ] Instanced Rendering (in progress)
- [ ] (Async?) file writer
- [ ] Clean Up the Code

### Nice to have
The following would be nice to have, but could also be implemented in follow-up PRs to reduce the diff.
- [ ] Add support for "exotic" stuff (`Scene` subclasses, `ImageMobject`, `Mesh`es, etc.)

## Follow-Ups
- [ ] Caching
- [ ] Plugin Hooks
