### ISSUE TITLE
v0.2.0 Roadmap

### ISSUE THREAD

**Issue by eulertour** [ManimCommunity/manim#588]
# Things to discuss
What projects do we want to divide the repo into? Here are a few off the top of my head:
- Documentation
- LaTeX
- GUI
- CONFIG

any others?

# Things to implement
- [x] #7
- [x] #473 (one person reported that this was fixed)
- [x] #572
- [ ] #589
- [x] make PangoText the default backend of Text (#487)
- [ ] invite developers of other manim-related projects to become part of the organization (or at least ask them to support manim CE). For example: https://github.com/krassowski/jupyter-manim

**Comment by leotrs** [comment]
Nitpick: are we going to have all of this ready for v0.2 (i.e. in a month)? If not, I'd suggest calling this issue "roadmap" instead of having to change the versionmilestone every month to update the items we didn't get to :sweat_smile:

**Comment by cobordism** [comment]
I think 0.1.1 is next ;)

**Comment by leotrs** [comment]
Oh. Right. But still, is this issue tracking a general roadmap of All The Things? Or the pending issues before the next release?

**Comment by eulertour** [comment]
Yeah it's only a roadmap, we plan to make the release whether or not we reach all the goals.

**Comment by leotrs** [comment]
I checked off a couple of items that are done.

@cobordism and I have a WIP fof #7, see #763 

Did anyone reach out to developers of other projects?
